services:
  cryptography:
    build: .
    ports:
      - "8089:8089"
    environment:
      GO_ENV: "production"
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    network_mode: "host"
